// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiSALw7DfN4sncKPiOMm3AlPG1AwDFamk',
    appId: '1:677657745369:web:41a066ee699b23b401ebc8',
    messagingSenderId: '677657745369',
    projectId: 'mypr-a0b9b',
    authDomain: 'mypr-a0b9b.firebaseapp.com',
    databaseURL: 'https://mypr-a0b9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypr-a0b9b.firebasestorage.app',
    measurementId: 'G-ZXMWS59WFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlbVzItVBwMdyykYN-MqAA1qpGkQIA-KU',
    appId: '1:677657745369:android:043357e23850b7f801ebc8',
    messagingSenderId: '677657745369',
    projectId: 'mypr-a0b9b',
    databaseURL: 'https://mypr-a0b9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypr-a0b9b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOQcn99Uy0uS19mQbE5fJml4hwhnsmEU',
    appId: '1:677657745369:ios:a44bf8e00a584c5301ebc8',
    messagingSenderId: '677657745369',
    projectId: 'mypr-a0b9b',
    databaseURL: 'https://mypr-a0b9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypr-a0b9b.firebasestorage.app',
    iosBundleId: 'com.example.kiwini',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOQcn99Uy0uS19mQbE5fJml4hwhnsmEU',
    appId: '1:677657745369:ios:a44bf8e00a584c5301ebc8',
    messagingSenderId: '677657745369',
    projectId: 'mypr-a0b9b',
    databaseURL: 'https://mypr-a0b9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypr-a0b9b.firebasestorage.app',
    iosBundleId: 'com.example.kiwini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiSALw7DfN4sncKPiOMm3AlPG1AwDFamk',
    appId: '1:677657745369:web:41a066ee699b23b401ebc8',
    messagingSenderId: '677657745369',
    projectId: 'mypr-a0b9b',
    authDomain: 'mypr-a0b9b.firebaseapp.com',
    databaseURL: 'https://mypr-a0b9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypr-a0b9b.firebasestorage.app',
    measurementId: 'G-ZXMWS59WFG',
  );
}
